### ISSUE TITLE
Virtual Hue, Physical Button?

### ISSUE THREAD

**Issue by riaandeyzel** [blocke/ha-local-echo#5]
I am trying to add a Emulated Hue device to Home Assistant.
I am running a Raspberry Pi 3 with Home Assistant 0.41.0 installed.
I have also added the lights component (platform: hue) to make sure that it installs the phue deps.
When I enter the following commands it all is successful:
http://:8300/description.xml
http://:8300/api/pi/lights

This is in my configuration.yaml file:
```
emulated_hue:
  type: alexa
  host_ip: 10.0.0.3
  listen_port: 80
#  advertise_ip: 10.0.0.10
#  advertise_port: 8080
#  off_maps_to_on_domains:
#    - script
#    - scene
#  expose_by_default: false
#  exposed_domains:
#    - light
#    - switch
```

When I do a search with the Phillips Hue app on my phone it detects the Emulated Hue device, but when I click on the Set up button the message reads " Press the push-links button on the Hue bridge you want to connect to.", and a progress line counts down, it then just returns to the search screen again.(Stuck in a loop).

The goal is to control my lights via Home Assistant by using Alexa (DIY: https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi) The Alexa part works just fine, and I have added the Philips Hue component to my Alexa Skills, but I need the Emulated Hue to be added to the meethue.com or phone app to work with Alexa and HA.

I am not sure if Philips realized this workaround their device and implemented the step where you have to physically click a button?.
